# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
      paths:
      - 'DemoProject/**'

jobs:
  demo_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./DemoProject/DemoProject.sln
      
    - name: Build
      run: dotnet build ./DemoProject/DemoProject.sln --no-restore
      
    - name: Unit Tests
      id: UnitTests
      run: dotnet test ./DemoProject/DemoProject.sln --filter "TestCategory=OnBuild" --no-build --verbosity normal

    - name: Backend Tests
      if: steps.UnitTests.outcome == 'success' && failure()
      run: dotnet test ./DemoProject/DemoProject.sln --filter "TestCategory!=OnBuild" --no-build --verbosity normal