# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
      paths:
      - 'ui_tests_playwright/**'

jobs:
  demo_job:

    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No tests execution required"'
